### ISSUE TITLE
use android system NSD_SERVICE replace jmdns

### ISSUE THREAD

**Issue by zhubinsheng** [warren-bank/Android-Bonjour-WebRTC#3]
NsdManager nsdManager = (NsdManager) getSystemService(NSD_SERVICE);

**Comment by warren-bank** [comment]
Hi. You're not wrong. This project already has a [minSdkVersion](https://github.com/warren-bank/Android-Bonjour-WebRTC/blob/v01.03.09/android-studio-project/constants.gradle#L5) that's &gt;= 16, so [`NsdManager`](https://developer.android.com/reference/android/net/nsd/NsdManager) should work.

Trouble is.. I've never tried it. In my experience, things rarely work off the shelf, as advertised. So, at least for now, I'm learning in the direction of: _if it ain't broken.._

As with all things open-source with a copy-left GPL, feel free to fork and experiment.
